### ISSUE TITLE
issue with t_renderer

### ISSUE THREAD

**Issue by alhaddad-m** [Tim-Salzmann/l4casadi#12]
Hi Tim! I have run my implementation with l4casadi and Acados and it works fine. However, in last time I have executed again `pip install .` . After this moment I couldn't run my implementation as before. Now I have the following error when i run my code. I have installed l4casadi again but the error still the same.

```
  File "/home/vladislav/.local/lib/python3.9/site-packages/l4casadi/template_generation/render.py", line 88, in render_template
    raise Exception(f'Rendering of {in_file} failed!\n\nAttempted to execute OS command:\n{os_cmd}\n\n')
Exception: Rendering of casadi_function.in.cpp failed!

Attempted to execute OS command:
/home/vladislav/.local/lib/python3.9/site-packages/l4casadi/template_generation/bin/t_renderer '/home/vladislav/.local/lib/python3.9/site-packages/l4casadi/template_generation/c_templates_tera/**/*' 'casadi_function.in.cpp' 'y_expr.json' 'y_expr.cpp'
```
Any suggestion?
Best kind!

**Comment by Tim-Salzmann** [comment]
Hi Muhammad,

can you please check that `/home/vladislav/.local/lib/python3.9/site-packages/l4casadi/template_generation/bin/t_renderer` exists? If it does exists please delete the 't_renderer' binary. It should be installed automatically during a L4CasADi run.

Could you additionally please state which OS you are running on.

Best
Tim

**Comment by alhaddad-m** [comment]
I am working on OS Ubuntu 20.04. I have deleted the file and while running code, it is downloaded as following
`Dowloading https://github.com/acados/tera_renderer/releases/download/v0.0.34/t_renderer-v0.0.34-linux
`However the error isn't fixed. The whole message is
```
Error: Failed to render 'casadi_function.in.cpp'
Reason: Variable `model_expects_batch_dim` not found in context while rendering 'casadi_function.in.cpp'
Traceback (most recent call last):
  File "/home/vladislav/l4casadi/examples/mpc_cnn_model_tested.py", line 622, in <module>
    acados_solver = create_solver(model_loaded , W , W_e)
  File "/home/vladislav/l4casadi/examples/mpc_cnn_model_tested.py", line 346, in create_solver
    model , l4c_model = robot_model(model_loaded)
  File "/home/vladislav/l4casadi/examples/mpc_cnn_model_tested.py", line 332, in robot_model
    model.cost_y_expr = vertcat(sym_x, sym_u , l4c_model(vertcat(sym_p,x,y,theta)))
  File "/home/vladislav/l4casadi/l4casadi_custom/l4casadi.py", line 32, in __call__
    return self.forward(*args)
  File "/home/vladislav/l4casadi/l4casadi_custom/l4casadi.py", line 45, in forward
    self.get_ready(inp)
  File "/home/vladislav/l4casadi/l4casadi_custom/l4casadi.py", line 71, in get_ready
    self.generate_cpp_function_template(rows, cols, has_jac, has_hess)
  File "/home/vladislav/l4casadi/l4casadi_custom/l4casadi.py", line 104, in generate_cpp_function_template
    render_template(
  File "/home/vladislav/.local/lib/python3.9/site-packages/l4casadi/template_generation/render.py", line 88, in render_template
    raise Exception(f'Rendering of {in_file} failed!\n\nAttempted to execute OS command:\n{os_cmd}\n\n')
Exception: Rendering of casadi_function.in.cpp failed!

Attempted to execute OS command:
/home/vladislav/.local/lib/python3.9/site-packages/l4casadi/template_generation/bin/t_renderer '/home/vladislav/.local/lib/python3.9/site-packages/l4casadi/template_generation/c_templates_tera/**/*' 'casadi_function.in.cpp' 'y_expr.json' 'y_expr.cpp'
```

**Comment by alhaddad-m** [comment]
I have figured out the problem. I have used old `l4casadi.py` file in which there was `has_batch` and I didn't expect that it has been replaced in last version by `model_expects_batch_dim`. So I will close this issue. Thank you Tim. I hope I could compile C++ code with L4casadi.

**Comment by alhaddad-m** [comment]
Actually, I have seen #9 before. However I still have some issues related to it. Let's me ask you here please. I have formulated CMakeLists.txt and added libraries of L4CasADi as following:

```
include_directories(
${PROJECT_SOURCE_DIR}/src/_l4c_generated
/home/vladislav/l4casadiv2/l4casadi/libl4casadi/include
/home/vladislav/l4casadiv2/l4casadi/libl4casadi
/home/vladislav/l4casadiv2/l4casadi/l4casadi/lib
)
target_link_libraries(target
	/home/vladislav/l4casadiv2/l4casadi/l4casadi/lib/libl4casadi.so
	${PROJECT_SOURCE_DIR}/src/l4c_generated/liby_expr.so
	${acados_lib}/libacados.so)
```
But here I have some 2 issues which I think they mention to l4casadi
```
/usr/bin/ld: libmpb_planners.a(y_expr.cpp.o): undefined reference to symbol '_ZN8L4CasADi4hessEPKdiiPd'
/usr/bin/ld: /home/vladislav/l4casadiv2/l4casadi/l4casadi/lib/libl4casadi.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mpc_planner.dir/build.make:186: /home/vladislav/bench-mr/bin/mpc_planner] Error 1
make[1]: *** [CMakeFiles/Makefile2:355: CMakeFiles/mpc_planner.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
