### ISSUE TITLE
Compilation on Windows

### ISSUE THREAD

**Issue by pariterre** [Tim-Salzmann/l4casadi#59]
Hi there! We are planning to use l4casadi in optimal control (in conjonction with bioptim). For that, I was trying to compile l4casadi with Windows.

This actually works just fine, except when using `pip install .`. The reason is that, for some reason the flag "/WX" is automatically set ("treat warning as error"). Unfortunately, there is one warning which I cannot solve. I am pasting you the full output of the compilation. Please note the relevant line contains "error C2220" (sorry for the french output, my computed is set to my native language)

```bash
Building wheels for collected packages: l4casadi

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.


      -- The C compiler identification is MSVC 19.32.31329.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.32.31329.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (1.8s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/pariterre/AppData/Local/Temp/pip-install-rec062we/l4casadi_0eae4a405bcb4349854e3634f69639c9/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\_skbuild\win-amd64-3.12\cmake-build
        Command:
          'C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\libl4casadi' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Programmation\Anaconda3\envs\pianoptim\Scripts\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\_skbuild\win-amd64-3.12\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.12.2 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Programmation\Anaconda3\envs\pianoptim\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Programmation\Anaconda3\envs\pianoptim\Include' '-DPYTHON_LIBRARY:PATH=C:\Programmation\Anaconda3\envs\pianoptim\libs\python312.lib' '-DPython_EXECUTABLE:PATH=C:\Programmation\Anaconda3\envs\pianoptim\python.exe' '-DPython_ROOT_DIR:PATH=C:\Programmation\Anaconda3\envs\pianoptim' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Programmation\Anaconda3\envs\pianoptim\Include' '-DPython_LIBRARY:PATH=C:\Programmation\Anaconda3\envs\pianoptim\libs\python312.lib' '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Programmation\Anaconda3\envs\pianoptim\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Programmation\Anaconda3\envs\pianoptim' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Programmation\Anaconda3\envs\pianoptim\Include' '-DPython3_LIBRARY:PATH=C:\Programmation\Anaconda3\envs\pianoptim\libs\python312.lib' '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\numpy\core\include' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Programmation\Anaconda3\envs\pianoptim\Scripts\ninja' -DCMAKE_BUILD_TYPE=Release '-DCMAKE_TORCH_PATH=C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\torch'

      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.


      -- The C compiler identification is MSVC 19.32.31329.0
      -- The CXX compiler identification is MSVC 19.32.31329.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Torch: C:/Programmation/Anaconda3/envs/pianoptim/Lib/site-packages/torch/lib/torch.lib
      -- Could not find nvcc, please set CUDAToolkit_ROOT.
      CMake Warning (dev) at CMakeLists.txt:18 (find_package):
        Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
        --help-policy CMP0146" for policy details.  Use the cmake_policy command to
        set the policy and suppress this warning.

      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Programmation/Anaconda3/envs/pianoptim/Lib/site-packages/cmake/data/share/cmake-3.31/Modules/FindCUDA.cmake:712 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:18 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CUDA_TOOLKIT_ROOT_DIR not found or specified
      -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY)
      -- Configuring done (2.4s)
      -- Generating done (0.1s)
      -- Build files have been written to: C:/Users/pariterre/AppData/Local/Temp/pip-install-rec062we/l4casadi_0eae4a405bcb4349854e3634f69639c9/_skbuild/win-amd64-3.12/cmake-build  
      [1/3] Building CXX object CMakeFiles\l4casadi.dir\src\l4casadi.cpp.obj
      FAILED: CMakeFiles/l4casadi.dir/src/l4casadi.cpp.obj
      C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx86\x64\cl.exe  /nologo /TP -DTORCH_VERSION_MAJOR=2 -DTORCH_VERSION_MINOR=5 -DTORCH_VERSION_PATCH=1 -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -Dl4casadi_EXPORTS -IC:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\libl4casadi\include -external:IC:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\torch\include -external:IC:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\torch\include\torch\csrc\api\include -external:W0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MD /O2 /Ob2 /DNDEBUG -std:c++17 /EHsc /bigobj -WX /showIncludes /FoCMakeFiles\l4casadi.dir\src\l4casadi.cpp.obj /FdCMakeFiles\l4casadi.dir\ /FS -c C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\libl4casadi\src\l4casadi.cpp
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\optional(82): error C2220: l'avertissement suivant est trait‚ comme une erreur       
      C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\libl4casadi\src\l4casadi.cpp(401): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::_Optional_destruct_base<_Ty,true>::_Optional_destruct_base<const unsigned __int64>(std::in_place_t,const unsigned __int64 &&)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\libl4casadi\src\l4casadi.cpp(401): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::_Optional_destruct_base<_Ty,true>::_Optional_destruct_base<const unsigned __int64>(std::in_place_t,const unsigned __int64 &&)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\optional(238): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::_Optional_construct_base<_Ty>::_Optional_construct_base<const unsigned __int64>(std::in_place_t,const unsigned __int64 &&)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\optional(238): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::_Optional_construct_base<_Ty>::_Optional_construct_base<const unsigned __int64>(std::in_place_t,const unsigned __int64 &&)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\torch\include\ATen/core/function_schema.h(437): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::optional<int32_t>::optional<const I,0>(_Ty2 &&)' en cours de compilation
              with
              [
                  I=size_t,
                  _Ty2=size_t
              ]
      C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\torch\include\ATen/core/function_schema.h(437): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::optional<int32_t>::optional<const I,0>(_Ty2 &&)' en cours de compilation
              with
              [
                  I=size_t,
                  _Ty2=size_t
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\optional(82): warning C4267: 'initialisation'ÿ: conversion de 'size_t' en 'int', perte possible de donn‚es
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xutility(142): warning C4267: 'initialisation'ÿ: conversion de 'size_t' en '_Ty', perte possible de donn‚es
              with
              [
                  _Ty=int
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(813): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'void std::_Construct_in_place<int,size_t&>(_Ty &,size_t &) noexcept' en cours de compilation
              with
              [
                  _Ty=int
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(800): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_back_with_unused_capacity<size_t&>(size_t &)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(806): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_back_with_unused_capacity<size_t&>(size_t &)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(886): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_one_at_back<size_t&>(size_t &)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(888): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_one_at_back<size_t&>(size_t &)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\torch\include\torch/csrc/dynamo/compiled_autograd.h(482): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::emplace_back<size_t&>(size_t &)' en cours de compilation
              with
              [
                  _Ty=int32_t
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xmemory(673): warning C4267: 'initialisation'ÿ: conversion de 'size_t' en '_Objty', perte possible de donn‚es
              with
              [
                  _Objty=int
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(836): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,size_t&>(_Alloc &,_Objty *const ,size_t &)' en cours de compilation
              with
              [
                  _Alloc=std::allocator<int>,
                  _Ty=int,
                  _Objty=int
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(860): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,size_t&>(_Alloc &,_Objty *const ,size_t &)' en cours de compilation
              with
              [
                  _Alloc=std::allocator<int>,
                  _Ty=int,
                  _Objty=int
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(800): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'int *std::vector<int32_t,std::allocator<int>>::_Emplace_reallocate<size_t&>(int *const ,size_t &)' en cours de compilation
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(809): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'int *std::vector<int32_t,std::allocator<int>>::_Emplace_reallocate<size_t&>(int *const ,size_t &)' en cours de compilation
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\utility(190): warning C4267: 'initialisation'ÿ: conversion de 'size_t' en '_Ty1', perte possible de donn‚es
              with
              [
                  _Ty1=int
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xutility(142): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::pair<int,int>::pair<size_t&,int&,0>(_Other1,_Other2) noexcept' en cours de compilation
              with
              [
                  _Other1=size_t &,
                  _Other2=int &
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xutility(149): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'std::pair<int,int>::pair<size_t&,int&,0>(_Other1,_Other2) noexcept' en cours de compilation
              with
              [
                  _Other1=size_t &,
                  _Other2=int &
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(813): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle 'void std::_Construct_in_place<std::pair<int,int>,size_t&,int&>(_Ty &,size_t &,int &) noexcept' en cours de compilation
              with
              [
                  _Ty=std::pair<int,int>
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(800): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_back_with_unused_capacity<size_t&,int&>(size_t &,int &)' en cours de compilation
              with
              [
                  _Ty=std::pair<int,int>
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(806): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_back_with_unused_capacity<size_t&,int&>(size_t &,int &)' en cours de compilation
              with
              [
                  _Ty=std::pair<int,int>
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(886): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_one_at_back<size_t&,int&>(size_t &,int &)' en cours de compilation
              with
              [
                  _Ty=std::pair<int,int>
              ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(888): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_one_at_back<size_t&,int&>(size_t &,int &)' en cours de compilation
              with
              [
                  _Ty=std::pair<int,int>
              ]
      C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\torch\include\torch/csrc/dynamo/compiled_autograd.h(476): note: voir la r‚f‚rence … l'instanciation de la fonction modŠle '_Ty &std::vector<_Ty,std::allocator<_Ty>>::emplace_back<size_t&,int&>(size_t &,int &)' en cours de compilation
              with
              [
                  _Ty=std::pair<int,int>
              ]
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\skbuild\setuptools_wrap.py", line 668, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\skbuild\cmaker.py", line 696, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\skbuild\cmaker.py", line 741, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          'C:\Programmation\Anaconda3\envs\pianoptim\Lib\site-packages\cmake\data\bin/cmake.exe' --build . --target install --config Release --
        Install target:
          install
        Source directory:
          C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9
        Working directory:
          C:\Users\pariterre\AppData\Local\Temp\pip-install-rec062we\l4casadi_0eae4a405bcb4349854e3634f69639c9\_skbuild\win-amd64-3.12\cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for l4casadi
Failed to build l4casadi
ERROR: Could not build wheels for l4casadi, which is required to install pyproject.toml-based projects
```

I tried to manually set `$env:CFLAGS="/W-` (OFF), but I get : 

```bash
# SAME OUTPUT WITH THIS EXTRA LINE
warning D9025ÿ: substitution de '/WX-' par '/WX'
```
which basically means both /WX and /WX- are set so it ignores my cries...

Any idea why fail on warning is set (or how to fix the warnings)?

Thanks!

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out. Unfortunately, I have not worked on Windows for years so I was never able to try L4CasADi on Windows. That being said, it looks like many would like to use it on Windows, so it would be fantastic if you could get this to work.

In [1] there are arguments passed to CMAKE. Possibly adding the right flag here could help?

Let me know if this works!

Thanks
Tim

[1] https://github.com/Tim-Salzmann/l4casadi/blob/c4d7b2eff85751ea7356b000486f5cab976efe96/setup.py#L36

**Comment by Tim-Salzmann** [comment]
Hi,

any luck here?

Thanks
Tim

**Comment by pariterre** [comment]
Haven't tried since as I had other things to do before the Christmas break... I'll take a another shot at it in January!

**Comment by pariterre** [comment]
Okay.. I spent way to much time on this... After trying everything I could think of, I've decided that error on warning needed to be set as it is not the default option... 
4th line of the CMakeLists.txt : 
set(CMAKE_COMPILE_WARNING_AS_ERROR ON)

Setting that to OFF obviously works.

I did not find this line as CMAKE_COMPILE_WARNING_AS_ERROR was introduced 3.24 of CMake and I did not know about it (as I am using older CMake versions for my projects).

I would suggest to set this to OFF by default and only setting this to ON for the developpers (maybe ON only on Debug?). 

Whatever you chose, I made a PR so you guys can discuss this at the right place

**Comment by Tim-Salzmann** [comment]
PR was merged. Thanks again!

**Comment by lclemen** [comment]
I would recommend reopening this. I had trouble installing this and had to change line 1 of CMakeLists.txt

`cmake_minimum_required(VERSION 3.0)` to `cmake_minimum_required(VERSION 3.15) `

There is something funky going on
